# Generated by Django 4.2.7 on 2024-02-08 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pending_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='team',
            field=models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='pending_team', to='api.team'),
        ),
    ]
