# Generated by Django 4.2.7 on 2023-12-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Member',
        ),
    ]
