# Generated by Django 5.0 on 2023-12-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_team_rename_user_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="email",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="password",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="member",
            name="first_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="member",
            name="last_name",
            field=models.CharField(max_length=20),
        ),
    ]
