# Generated by Django 5.0 on 2023-12-05 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_course"),
        ("api", "0005_lecture"),
    ]

    operations = []
