# Generated by Django 4.2.7 on 2023-12-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_member_email_alter_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='course_id',
            field=models.IntegerField(max_length=20),
        ),
    ]
