# Generated by Django 4.2.7 on 2023-12-16 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_member_email_alter_member_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
    ]
