# Generated by Django 4.2.7 on 2023-12-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_course_name_course_title_and_more'),
        ('api', '0010_rename_first_name_member_name_and_more'),
        ('api', '0011_alter_lecture_course_id'),
    ]

    operations = [
    ]
