# Generated by Django 4.2.7 on 2023-12-23 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20231222_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lecture', models.ForeignKey(db_column='lecture_id', on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='api.lecture')),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='member', to='api.member')),
            ],
        ),
    ]
