# Generated by Django 4.2.7 on 2024-01-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_course_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=64),
        ),
    ]
