# Generated by Django 4.2.7 on 2024-02-04 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(db_column='team_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='api.team'),
            preserve_default=False,
        ),
    ]
