# Generated by Django 4.2.7 on 2024-02-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_member_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="role",
            field=models.CharField(default="member", max_length=10),
        ),
    ]
