# Generated by Django 4.2.7 on 2024-02-05 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_team_team_name_member_role_team_abbreviation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_name',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default='member', max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ForeignKey(db_column='team_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='api.team'),
        ),
    ]
