name: Build and Deployment

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.11]

    steps:
    - uses: actions/checkout@v2
    - name: Django aws eb deployment
      uses: joel-hanson/django-aws-eb-deploy@V1.1
      with:
        python_version: ${{ matrix.python_version }}
        aws_access_key_id: ${{ secrets.ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
        deploy: true
